domain_path: E:\EDABK\Workspace\platform\lab1_platform\export\lab1_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
